version: '3'

services:
  db:
    image: mysql
    container_name: arristool_db
    restart: unless-stopped
    env_file: ./app.env
    volumes:
      - ./data:/var/lib/mysql

  arristool:
    image: arristool:latest
    restart: unless-stopped
    container_name: arristool
    hostname: arristool.speedconnect.net
    ports:
      - 3000:3000
    env_file: ./app.env
    environment:
      - INITDB=0
    volumes:
      - ./:/app
      - ./share:/share
    depends_on:
      - db
    links:
      - db

networks:
  default:
    external:
      name: services-network

